apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysqlservice
  name: mysqlservice
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysqlservice
status:
  loadBalancer: {}
