apiVersion: v1
kind: Service
metadata:
  labels:
    app: sim-activation
  name: sim-activation
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: sim-activation
