apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-validation
  name: user-validation
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    app: user-validation
